### ISSUE TITLE
Particle without texture shows texture

### ISSUE THREAD

**Issue by DelvarWorld** [squarefeet/ShaderParticleEngine#100]
I have an emitter that only has color in the constructor, but the particles have a texture used elsewhere in my game. I think it's just reading from the leftover render something buffer. Setting texture: null doesn't remove the texture from the particles.

**Comment by DelvarWorld** [comment]
This isn't right. Looking for a workaround, which might mean a USE_TEXTURE define

**Comment by DelvarWorld** [comment]
Oooooh I didn't realize that a texture was required. my bad. I just assumed it would be some kidn of glowing point without a texture specififed.

**Comment by squarefeet** [comment]
Ah, you stumbled upon something that I meant to sort out a while back: support for !texture.

Thanks for accidentally reminding me!
