### ISSUE TITLE
no display on Firefox with Threejs r75 and r76

### ISSUE THREAD

**Issue by Grajon** [squarefeet/ShaderParticleEngine#107]
Hi,

rendered scenes are correct on Chrome with Threejs r75 and r76, but nothing apears on Firefox (v48 dev, v47 dev  and v45)

same thing with the example named explosion

Thanks for your great work, and sorry for my bad english :)

**Comment by squarefeet** [comment]
Does the same thing happen with Threejs r73?

I'll look into this, and thanks for letting me know.

**Comment by Grajon** [comment]
Yes on Windows, 7 (32 and 64 bits with SP1) and XP SP3. Tomorrow I will made a test under Debian 8.2

I have not tested with threejs r73. And not all examples don't work, just some of them: explosion, fog and Emitter pooling.

I have made a smoke engine with your engine, it works well under Chrome and other webkit engines (like Opera), but not on FF (release, dev and aurora tested)

Thanks for your help

**Comment by squarefeet** [comment]
Hey @Grajon, sorry for being so tardy. Very busy with real life lately.

Interesting that removing the floor mesh fixes the issue on Win7... by the sounds of it, I'd put it down to either a ThreeJS issue or Firefox itself. 

Are you still seeing problems with both the latest ThreeJS and latest Firefox releases?
