### ISSUE TITLE
Firefox 46 Emitter Pool not visible

### ISSUE THREAD

**Issue by weiserhei** [squarefeet/ShaderParticleEngine#108]
I noticed the emitter pool examples doesnt work with the latest Firefox 46.0 (on windows) anymore. 
In particular these examples:
http://squarefeet.github.io/ShaderParticleEngine/examples/explosion.html
http://squarefeet.github.io/ShaderParticleEngine/examples/fog.html
http://squarefeet.github.io/ShaderParticleEngine/examples/pool.html

No particles visible, and no errors in the console. Im using Threejs R76 previously without problems, doesnt work there too.

Probably something mozilla has to look after, this issue is for keeping track of it.

**Comment by RemusMar** [comment]
I don't have any issue with Firefox 46.0.1 and those examples.
You need to provide more details about your system (OS, graphics card, etc)

**Comment by weiserhei** [comment]
**System spec**
Windows 10
Firefox 46.0.1
Geforce GTX 970

**Test case**
Three.js r76
SPE 1.0.5
All the examples in my first post dont show particles,
and also older [demos](http://weiserhei.github.io/threejs-experiments/christmas2015/) ive build that were working before. 
In **Chrome** and **Edge** everything is still working.

![particles](https://cloud.githubusercontent.com/assets/7581732/15319523/873282ee-1c2b-11e6-89f7-98b71500b03f.png)

**Comment by RemusMar** [comment]
Please test this benchmark with Firefox 46:
http://necromanthus.com/Test/html5/testA.html 
You should see 4 particle emitters: 2x steam, fire and smoke

**Comment by weiserhei** [comment]
Fire and smoke is visible, steam is not.

**Comment by RemusMar** [comment]
> Fire and smoke is visible, steam is not.

Very hard to believe.
The smoke and the steam share the same resources (including the texture).

**Comment by squarefeet** [comment]
Any update on this @weiserhei?

**Comment by weiserhei** [comment]
Firefox 47.0.1 here, problems "disappeared" on my demos. Closing this now.
