### ISSUE TITLE
change emitter velocity

### ISSUE THREAD

**Issue by danni-san** [squarefeet/ShaderParticleEngine#11]
Hi,

I tried to change the velocity on a running emitter.
Changing the position or particlesPerSecond works, e.g.:

particleGroup.emitters[0].position.add(new THREE.Vector3(11,15,10)); 

But velocity/velocitySpread/size wont take the changes.

I tried to break down the code and it looks like the velocity is created on addEmitter, but I cant figuere out why position change works buw velocity dont.

Can you give me a clue how I could add that feature or is it a bad idea (performance)?

greets

**Comment by DelvarWorld** [comment]
I'm needing this functionality in my game - is this available at all on the latest master build?

If it's expensive and has to live in a branch, I think some kind of setter method would be useful here?

**Comment by DelvarWorld** [comment]
Oh I see, I was confused about the syntax for this (couldn't find any documentation for it).

This is the correct syntax:

```js
emitter.velocity.value = ...
``` 

and not

```js
emitter.velocity = {
    value: ...
};
```

and not the hack:


```js
emitter.velocity = {
    _value: ...
};
```
