### ISSUE TITLE
NPM Build Assumes `window.THREE` Exists

### ISSUE THREAD

**Issue by msimpson** [squarefeet/ShaderParticleEngine#110]
While this library has module loader support by way of:

```
// Module loader support:
if ( typeof define === 'function' && define.amd ) {
    define( 'spe', SPE );
}
else if ( typeof exports !== 'undefined' && typeof module !== 'undefined' ) {
    module.exports = SPE;
}
```

Using `module.exports` to expose the SPE object is not sufficient without also requiring THREE as a dependency. Therefore, this library--always--needs to be shimmed to even function when loaded via NPM.

**Comment by squarefeet** [comment]
Thanks, I'm on it (finally).
