### ISSUE TITLE
Change position of the emitter?

### ISSUE THREAD

**Issue by anothercoder2** [squarefeet/ShaderParticleEngine#111]
Is it possible to change the position of the emitter?
I tried changing the position of the emitter but it does not seem to work.
e.g
particleGroup.emitters[2].position.value.z = particleGroup.emitters[2].position.value.z +10;

The position value changes but there is no update on the screen.

**Comment by mwcz** [comment]
Try this:

    particleGroup.emitters[2].position._value.z += 10;
    particleGroup.emitters[2].updateFlags.position = true;

**Comment by jhclaura** [comment]
This also happened to other parameters e.g. velocity, acceleration. Wonder what's the purpose of this safety measures? Performance?
It'd be useful if the change can take effect without setting the flags, so they can be animated with some Tweening libraries.

**Comment by mwcz** [comment]
I'm sure you're right that performance is the reason.  it's a [dirty flag](http://gameprogrammingpatterns.com/dirty-flag.html).  threejs uses a similar pattern, it's just called `needsUpdate` instead.

I would guess that most tweening libraries would allow you to pass in an "onUpdate" function, within which you could set `updateFlags`.

**Comment by squarefeet** [comment]
So I'm totally late to the party on this one, but if you're needing to update values in real time and the value you're changing is a property like `x` on `emitter.position.value`, then you need to re-trigger the setter for `emitter.position.value`.

The simplest way to do this is:

`emitter.position.value = emitter.position.value`.

It looks a bit silly, but it works! I'm finally giving the library some love, and have added in an `update()` function to the Emitter class, and an `updateAll()` function to the Group class that will do this silliness for you if you're finding you're changing properties and nothing is happening. I hope to release it very soon :)

**Comment by JasXSL** [comment]
A problem with this is that it seems to cause velocity to break, sending the particles flying in the direction of where they were first added.
