### ISSUE TITLE
The particles are not displayed when moving the camera

### ISSUE THREAD

**Issue by korner-brazers** [squarefeet/ShaderParticleEngine#113]
Hi, I noticed a bug, if you move and rotate the camera in certain corners of the particles disappear from the screen.
I use EditorControls.js of three.js library and stir the particle at position 3000, 0, 300
If you move the camera at different positions and look at the particle appears this bug! Maybe something I forgot to add this real or a bug?

Here are a couple of screenshots.

![](http://dtf.su/fea9113d.png)

![](http://dtf.su/f9ad1a9f.png)

**Comment by squarefeet** [comment]
It's going to be difficult to reproduce this, could you make an online version (JSBin or similar) that I can look at?

**Comment by korner-brazers** [comment]
Oh sure)
http://codepen.io/korner/pen/BLLNVX

**Comment by rafaelcastrocouto** [comment]
Also happens in my project. How can we solve it?

**Comment by squarefeet** [comment]
Could one of you try setting the following property on your group(s) and see if it fixes the issue?

`group.mesh.frustumCulled = false`

**Comment by rafaelcastrocouto** [comment]
Yes @squarefeet it fixes the issue
http://codepen.io/rafaelcastrocouto/pen/jyKMYE
You can close it!

**Comment by squarefeet** [comment]
Yay! Glad that worked, saves me a lot of digging around :)
