### ISSUE TITLE
Random rotation of individual particles

### ISSUE THREAD

**Issue by dr2391** [squarefeet/ShaderParticleEngine#114]
Hi, I'm having trouble figuring out how to give individual particles a random rotation direction and speed. Using Emitter.angle seems like I'm only able to set the rotation direction for all particles. The spread value is probably the answer but I'm not really sure of how to use it. Here's what I have:

`angle: {
    value: [ -Math.PI, Math.PI ],
    randomise: true,
}`

**Comment by mwcz** [comment]
I got something similar working with the following:

                angle: {
                    value: [0],
                    spread: [2*Math.PI, 0],
                },

Each particle is spawned with a random rotation between -2Pi..2Pi radians, then spends its life rotating back to 0 radians.
