### ISSUE TITLE
does any demo about rain or snow?

### ISSUE THREAD

**Issue by dyh333** [squarefeet/ShaderParticleEngine#116]
hi, @squarefeet . I am learning your ParticleEngine repo. the examples are all cool, but would you please give a demo about rain or snow like stemkoski's this page?
https://github.com/stemkoski/stemkoski.github.com/blob/master/Three.js/Particle-Engine.html

thanks.

**Comment by weiserhei** [comment]
This is my snow demo: http://weiserhei.github.io/threejs-experiments/christmas2015/
Its based roughly on stemkoski in a simple scene and the code is on github: https://github.com/weiserhei/threejs-experiments/blob/gh-pages/christmas2015/js/app/snowParticles.js

**Comment by dyh333** [comment]
@weiserhei  thanks. it works well.

**Comment by squarefeet** [comment]
Hi @dyh333. To change texture at run-time, you'll have to do a few things. I'll give you an example below. I'm currently working on quite a few additions to this library (it's been a while!) and one of them will be a function on SPE.Group that will do this for you. In the meantime, to change a texture on a particleGroup once you've created it (and following your example above):

```
particleGroup.texture = loadTexture( './img/snowflake.png' );
particleGroup.uniforms.texture.value = particleGroup.texture;
particleGroup.material.needsUpdate = true;
```

Hope that helps!

**Comment by dyh333** [comment]
@squarefeet  thanks very much. i will try.

**Comment by dyh333** [comment]
@squarefeet 
it works. thanks again.

**Comment by squarefeet** [comment]
Ah good, glad it worked :)
