### ISSUE TITLE
Examples don't work properly on Three.js r84

### ISSUE THREAD

**Issue by allanbueno** [squarefeet/ShaderParticleEngine#119]
This Particle Engine is awesome, but it is not working properly on Three.js r84.

When I tried to use the MultipleEmitters example with this version of Three.js, only one emitter is showed in the screen. There are other examples that don't work too, but I believe the problem is the same.

Thanks.

**Comment by squarefeet** [comment]
I noticed this a few days ago when I started doing some other bugfixes. I know the problem and have a fix in place already, but won't get released for a week or so until the rest of it is ready.

Would it help you if I issued a hotfix to master?

**Comment by allanbueno** [comment]
Thank you very much for replying so quickly.

Yes, a hotfix will be great to get it working sooner.

**Comment by squarefeet** [comment]
Sure, I'll get one out as soon as I can :)

**Comment by allanbueno** [comment]
OK, I will wait! Thanks again :)

**Comment by squarefeet** [comment]
I figured since I have a few spare moments I'd be best getting it done, so v1.0.6 is ready for you on master. I've not published to NPM yet, so if you're needing it as an NPM module, I should have that ready soon.

Let me know if this fixes your issue!

**Comment by allanbueno** [comment]
It is working perfectly now :)

Thank you again for replying and also for making this useful lib.

**Comment by squarefeet** [comment]
Awesome, thanks!
