### ISSUE TITLE
Prevent particles from following camera ? 

### ISSUE THREAD

**Issue by etiennepinchon** [squarefeet/ShaderParticleEngine#123]
Hi!

Love this library so far but I have little issue with it, I cannot find a way to prevent the particles from rotating and tracking the camera when it moves.

I want the particles to stay in the same orientation, is it possible?

Thank you!

**Comment by squarefeet** [comment]
Hi @etiennepinchon,

Do you mean that you wish the particles to not always face the camera? If so, then unfortunately that's not going to be possible. The particles are rendered as 'billboards' - these are 2D objects, not 3D, so can't be rotated in 3D space.

**Comment by etiennepinchon** [comment]
Hi @squarefeet, thank you for you quick response!
Yes exactly what I wanted to do (similar to the things we can do with Unity)!

- Would it be possible to render the particles on a quad that would then be rotated?

Btw, your engine is by far the most advanced one I have seen on the web, really amazing work! 👍

**Comment by squarefeet** [comment]
Thanks man :)

It's definitely possible, but it would require rewriting most of the library! Internally, the library uses a `THREE.Points` instance, which is what causes the billboard behaviour.

I daresay that if you wanted an adventure, you could replace `THREE.Points` with a constructor to render quads instead!

**Comment by squarefeet** [comment]
Closing this as mesh-based particles are out of scope for this project.
