### ISSUE TITLE
Three r118 Breaking Changes

### ISSUE THREAD

**Issue by titansoftime** [squarefeet/ShaderParticleEngine#134]
Three.js r118 creates a WebGL2 context by default. The name `texture` for a variable in webgl2 shader code is invalid as the function name `texture2D` was replaced by `texture`, making `texture` a reserved word that cannot be used as a variable.

In my local copy I just renamed `texture` to `tex`. Don't forget to update the uniform name in the js code as well.

Also `BufferAttribute.dynamic` has been removed. Instead of `BufferAttribute.dynamic = true;`, do `BufferAttribute.usage = THREE.DynamicDrawUsage; `.

**Comment by squarefeet** [comment]
Ah, thanks for letting me know. I'll try and find some time to push an update out soon... I've (rather shamefully) let this repo grow moss over the last few years.

Is this something that's blocking you?

**Comment by titansoftime** [comment]
No problem, man. Life happens.

It's a block if you want to use WebGL 2 context (which is default in the new 118 release of three.js).

Also the BufferAttribute.dynamic.true -> BufferAttribute.usage = THREE.DynamicDrawUsage seemed to fix some visual issues.

A real block was the issue at least worked around by  https://github.com/squarefeet/ShaderParticleEngine/pull/132 (this probably isn't the right approach, but at least it keeps the code running when fog is set to true).

Glad to see you post here =] Hope all is well.

**Comment by RemusMar** [comment]
Hi guys,

You can find the fix here: https://github.com/RemusMar/ShaderParticleEngine 

And here is a test with THREE r118: https://necromanthus.com/Test/html5/clouds.html 

cheers
