### ISSUE TITLE
3D Music Visualizer

### ISSUE THREAD

**Issue by cihadturhan** [squarefeet/ShaderParticleEngine#47]
I've found a guy on youtube which very cool 3D Music Visualizer using particle dynamics.

If you look [first](http://youtu.be/fpViZkhpPHk) and [fourth](http://www.youtube.com/watch?v=fpViZkhpPHk&t=1m52s) one, it seems very doable with this library. 

However, I'm not sure how to make particles behaves like smoke as you see in examples. Any ideas how to make it possible?

**Comment by rustinlee** [comment]
That looks to involve quite a bit of fluid dynamics, which is its own subject entirely.

Also:
>tools: 3ds max / Krakatoa / fumefx / after effects
>rendertimes: 10-40 sec / frame; quadcore i7 920 cpu

That many particles interacting as they do will not be possible for you to simulate in real time, let alone in a web browser.
