### ISSUE TITLE
Emitter disappearing with three.js r68

### ISSUE THREAD

**Issue by weiserhei** [squarefeet/ShaderParticleEngine#51]
Hello,
i tried to implement the basic particle emitter example using the latest three.js r68. 
I build a demo where the emitter stays in front of the camera and is pointed at it, which only seems to work with r65.

With r68 the emitter is disappearing when moving the camera and pops back in unpredictable.
Any ideas?

![particle](https://cloud.githubusercontent.com/assets/7581732/3820377/2ee53152-1cf7-11e4-963a-fe82756005b7.png)

http://three.thiele-medien.de/emitter.html
http://three.thiele-medien.de/emitter-r65.html

**Comment by gaepard** [comment]
Setting the boundingSphere position definitely do the work (ver. 0.7.5)
Thanks Usnul!

**Comment by weiserhei** [comment]
What Usnul suggested is working fine for me with SPE 0.7.9 and three.js 71, so i can leave frustum culling enabled :)
Thank you all!
