### ISSUE TITLE
bug with culling in Tree.js

### ISSUE THREAD

**Issue by Usnul** [squarefeet/ShaderParticleEngine#55]
Interesting problem. Culling is done using geometry bounding volume, and that's not computed propely for particle emitters, so if point "x:0, y:0, z:0" is not in camera's view - whole emitter gets culled. Need to address this by using infinite volumes or recomputing volumes every simulation tick (which is probably not practical?)

**Comment by DelvarWorld** [comment]
i'm running into this now - the whole emitter gets culled when the source goes off screen. was this issue actually resolved @squarefeet ?

**Comment by squarefeet** [comment]
It was resolved in the previous version, but by the sounds of it, it's re-emerged in the rewrite.

You should be able to set the particle mesh to not be frustum culled and that'll sort it...

**Comment by OpherV** [comment]
I can definitely reproduce the issue - and the solution @squarefeet suggested works for me. Took me a while to find this thread though - perhaps keep the issue open? :)

**Comment by squarefeet** [comment]
I'm keeping the issue closed, but I'll make a note to add it to the documentation.

**Comment by Usnul** [comment]
in case someone wants the cake and eat it too, here's what i do currently:
- keep culling on
- when emitter position changes - set bounding volume to infinite size (never culled basically)
- when enough time since last position change passes for all particles to have died from back then - compute bounding box based on physics (as in post earlier).

here are relevant snippets:

```
function setEmitterPositionFromTransform(emitter, transform) {

    const source = transform.position;
    const pO = emitter.positionOffset;

    const position = emitter.__speEmitter.position;


    const x0 = position.x;
    const y0 = position.y;
    const z0 = position.z;

    const x1 = source.x + pO.x;
    const y1 = source.y + pO.y;
    const z1 = source.z + pO.z;

    if (x0 !== x1 || y0 !== y1 || z0 !== z1) {
        position.set(x1, y1, z1);
        emitter.timeSincePositionChanged = 0;
        emitter.bvhLeaf.setInfiniteBounds();
        return true;
    } else {
        return false;
    }
}
```
```
//inside simulation tick
 setEmitterPositionFromTransform(emitter, transform);

        if (emitter.timeSincePositionChanged < emitter.maxAge && emitter.maxAge - emitter.timeSincePositionChanged <= timeDelta) {
            //sufficient time has past since last move, so that all particles currently alive fit inside local bounding box
            setBVHLeafBoundsFromBoundingBox(emitter, transform.position);
        }
//tick the group
        if (timeDelta > 0) {

            if (checkVisibility(emitter, frustums)) {
                //only perform updates on visible groups
                speGroup.tick(timeDelta);
            }
            emitter.timeSincePositionChanged += timeDelta;
        }
```
