### ISSUE TITLE
addEmitter/removeEmitter not working as expected

### ISSUE THREAD

**Issue by klebba** [squarefeet/ShaderParticleEngine#61]
This issue reflects the same problem described in #58, which was closed because the author found a workaround. The original problem raised about the behavior of addEmitter and removeEmitter still stands -- these features don't behave the way they are named. Using addEmitter some time after I've added the mesh of my SPE.Group to my scene has no effect; nothing is rendered. Calling removeEmitter just freezes the last state of the removed emitter in the scene.

Thanks!

**Comment by squarefeet** [comment]
Yep, you're spot on here. I've always liked the idea of having these functions, and to be quite honest with you, I regret adding them into ```master```, as they don't work as-advertised. If one knows the internals of THREE.js a little, one could extrapolate as to why this is, but without that information, it's silly them being there, and silly of me to expect everyone using this library knows that info.

The basic issue with these methods is that once a Geometry instance has been created, one can't adjust the number of vertices in it without causing what is essentially a re-instancing of the entire geometry. There should be a workaround for this, and I do remember having a play around with some options a while back, but had to abandon it in favour of more pressing updates for the library as a whole (time is always an issue). I have been working on a 2nd version of this library on and off for a while, and as it stands at the moment, adding and removing emitters does seem to be working.

I'm afraid that currently I don't have any time to look into this, which isn't a great answer for you, I know. One thing you could try, though, is altering the `duration` attribute of the emitter you want to remove. Setting it to a low number should cause it to die and stop being rendered. 

I hope that helps a little, and sorry I can't fix this for you right now.

**Comment by squarefeet** [comment]
Fixed in 1.0.0 beta. See #75.
