### ISSUE TITLE
readme.md unclear on required three.js

### ISSUE THREAD

**Issue by jpcloud** [squarefeet/ShaderParticleEngine#63]
Hi,

Just a quick question/note. The readme.md states:
"This project requires THREE.js revision 58 to revision 65."
Does this mean, that it will not work with THREE.js revisions higher than 65?
(Current stable three.js is rev 70)

If those are just the minimum required version, it should state that.
I am a little confused. (I'll now just try to get it to work with rev 70 :) )

**Comment by squarefeet** [comment]
You're right... It's not very clear, is it! It should work okay with versions higher than 65, though I haven't tested it myself with anything higher than rev 68. I'm not able to test with rev 70 for a while - could I ask you a favour to report back whether it works or not, and if not, what the issues are? 

I'll update the README accordingly. Thanks for pointing it out!

**Comment by jpcloud** [comment]
hi,
as far as I can tell it's working fine with rev 70.

http://i.imgur.com/r6EsmnU.gifv

It's my first time using it, I have taken the example from the readme and modified it a little to somewhat look like a rocket booster. Without recording the frame are at a steady 60 per second.

**Comment by squarefeet** [comment]
Ah fantastic - thanks for reporting back :)

Will update README. Cheers buddy.
