### ISSUE TITLE
Rotate disk in ShaderParticles.js

### ISSUE THREAD

**Issue by webtech1980** [squarefeet/ShaderParticleEngine#67]
When I add a emitter to my scene with the type of disk it always faces the same direction. Now I have noticed that you can rotate the hole mesh the particle system is applied to but that messes up my position settings. I'm trying to have the disk always face the camera of my three.js scene. Which Is often located at vector{0,0,0}. Any help would be greatly appreciated.

**Comment by squarefeet** [comment]
Ahh, this will be fairly complex to support... I'll stick it in my list of things to experiment with, but I'm afraid there probably won't be anything in the near future unless I hit upon a random bit of inspiration!

I'll definitely keep you updated should I manage to do anything with this.

**Comment by webtech1980** [comment]
Cool thanks.

**Comment by squarefeet** [comment]
I've added support for emitter rotation in v1.0.0. See `rotation` options for `SPE.Emitter` [here](https://squarefeet.github.io/ShaderParticleEngine/docs/api/global.html#EmitterOptions)
