### ISSUE TITLE
Particle size and camera FOV

### ISSUE THREAD

**Issue by RemusMar** [squarefeet/ShaderParticleEngine#72]
First of all, congrats for this awesome work.
Now the problem ...
The particles size (on screen) depends on the camera field of view.
This is a known issue, nothing to do about that.
However, if you change the emitter sizeStart and sizeEnd at runtime, you don't get any change on screen.
Example:
you start with camera.fov = 45, sizeStart = 0.5, sizeEnd = 1.0
at runtime you set camera.fov = 22.5, sizeStart = 1.0, sizeEnd = 2.0
The camera fov is changed ( camera.updateProjectionMatrix(); ), but the new sizeStart & sizeEnd values are ignored.
Result: you'll get smaller particles on the screen.

cheers

**Comment by RemusMar** [comment]
Well, I found a workaround:

			onParticleSpawn: function( attributes, particleIndex ) {
				attributes.size.value[ particleIndex ].set( 0.4 * zoom, 0.7 * zoom, 1.0 * zoom );
				attributes.size.needsUpdate = true;
			}

But it doesn't work for the already existing particles.
cheers

**Comment by Usnul** [comment]
Sadly this is quite normal as we're working with a TRHEE.Material here. You have to update materials when you make changes.

Also, this looks to be an anti-pattern. The point of a an engine is to define target states and remove responsibility of transition from the user.

**Comment by RemusMar** [comment]
Hi Alex,

The main problem is that the ShaderMaterial is embedded into the ShaderParticles.js package
and there is no way to pass the "size" value (sizeStart & sizeEnd) at runtime.
Or maybe I'm missing something here ...

cheers

**Comment by Usnul** [comment]
You probably don't mean this:
```js
var particleEmitter = new SPE.Emitter({
    sizeStart: 10,
    sizeEnd: 0,
});
```
Emitters aren't supposed to change much. But I see what you mean about embedding.
```js
group.material;
```
Material is exposed via "Group", you can access attributes there, maybe this will help.

**Comment by RemusMar** [comment]
Here is the "onParticleSpawn":
http://necromanthus.com/Test/html5/testA.html 
Take a look at the "steam" and press the right mouse button (a few times).
The result is not bad, but it can be better if the already existing particles would be scaled as well.

cheers

**Comment by RemusMar** [comment]
> You probably don't mean this:

var particleEmitter = new SPE.Emitter({
    sizeStart: 10,
    sizeEnd: 0,
});

> Emitters aren't supposed to change much. 

In fact emitter.sizeStart and emitter.sizeEnd need to be changed at runtime.
You don't want to change the size thousands of times (for every particle).
You need to change the size only once (for the current and upcoming particles).
But this is not possible with the current ShaderParticles.js package.

cheers

**Comment by RemusMar** [comment]
And here is the best workaround (with perfect results):

				for (var p = 0; p < emitter.attributes.size.value.length; p++) {
					emitter.attributes.size.value[ p ].set( 0.4 * zoom, 0.7 * zoom, 1.0 * zoom );
				}
				emitter.attributes.size.needsUpdate = true;

But you need to change the sizeStart, sizeMiddle & sizeEnd for all the current particles!
Instead of changing those values only once ...

http://necromanthus.com/Test/html5/testA.html
cheers

**Comment by Usnul** [comment]
The reason you wouldn't want to change it at run-time is because of GPU access, re-binding attribute arrays takes some time. I'm not sure how much though. It's not the same as rebuilding shader, but it's not free. Re-binding attributes of single value is also likely to be a lot cheaper than things like large arrays, such as in case of particles we have here. Just a word of caution; if this doesn't impact you enough - then i'm glad you found a good solution for yourself.

To clarify "rebinding" - when you set "needsUpdate = true", you request that GPU-bound values are to be scrapped and current data from javascript be written instead. If your array has 1000 elements and you just change 1 of them - still all 1000 will be written.

As much as I care about performance - depending on your use-case it's likely not an issue.

**Comment by RemusMar** [comment]
Alex,

You miss the main point here.
With that "workaround" I don't get any performances drop for 1500 particles.
Besides, you don't have to run it every frame!
You run it only when camera.fov is changed.

In any case, the solution to all of these is very simple:
- all the emitter.attributes need to be passed at runtime
- inside of the "tick" function: if an emitter parameter was updated, all the current particles must be updated
So depending on the emitter.attributes.parameter, that loop is performed for all the current particles.
That's all and nothing more.

cheers

**Comment by Usnul** [comment]
1500 particles is not much. Maybe fov handling souls be done in shader, that's the gist odd my point. Glad you're problem is solved :)

**Comment by RemusMar** [comment]
> Maybe fov handling souls be done in shader, that's the gist odd my point. 

If that's faster and it gives the same good results, I totally agree.
The bottom line:
the users must be able to pass at runtime the particle "size" ( in fact v3(sizeStart, sizeMiddle, sizeEnd) )
to the shader or to the emitter.
And all the current (and upcoming) particles must be updated after that.
But only once!

best regards

**Comment by squarefeet** [comment]
Hey @RemusMar / @Usnul,

Only just caught up on this (out of the country at the moment). 

@Usnul: many thanks for getting involved! As a little aside, v2 of this lib is still floating around in an... *interesting* state, but it does allow for runtime changes at least. One day... One day it will see a release!

@RemusMar: It looks like a solution has been found, but I have to agree that its not ideal. Runtime changes should really be an allowed thing, so I'll see what I can bake into the library for the next (minor, possibly major if the API changes as a result [something I will try damn hard to avoid!]).

I have an idea milling around in my head for this (thinking about getters/setters via `Object.defineProperty`), but it will require a fair amount of internal changes to do it "correctly"; it's not something I just want to hack in. It might also save a few cycles when respawning particles, which can only be a good thing.

I'll start playing around with some ideas soon and let you know how progress goes soon.

**Comment by Usnul** [comment]
as an aside. @squarefeet put some code up - I will get involved. It'll never be perfect :)

**Comment by RemusMar** [comment]
> I have an idea milling around in my head for this (thinking about getters/setters via Object.defineProperty), but it will require a fair amount of internal changes to do it "correctly"

Hi Luke,

It sounds like a good idea.

cheers

**Comment by squarefeet** [comment]
@Usnul: It's been a while since I last looked at it, but I'll have a gander tomorrow and see what state it's in. If it ain't too bad, I'll send you an invite to it so you can hack away as well. If it's a dire mess, I'll tidy it up a little and then do that.

@RemusMar: cool cool - I'll keep you informed on this thread :)

**Comment by adarshnambiar** [comment]
Hi all, I am really new to using THREE js and Particle Shader . I am currently creating a particle effect using this Shader Particle Engine.I want to change couple of variables during runtime  .I could change particlecount,velocity ,acceleration,type,blending,speed  but could not change colorStart,colorEnd along with startSize,endSize.I saw this thread and would like to ask if its a similiar issue with changing  color as well?or am i missing anything simple.
Thanks!

**Comment by RemusMar** [comment]
> could not change colorStart,colorEnd along with startSize,endSize

Probably the only workaround is the following:

		for (var p = 0; p < emitter.attributes.colorStart.value.length; p++) {
			emitter.attributes.colorStart.value[ p ].setRGB( 0.3, 0.2, 0.1 );
			emitter.attributes.colorMiddle.value[ p ].setRGB( 0.45, 0.3, 0.15 );
			emitter.attributes.colorEnd.value[ p ].setRGB( 0.6, 0.4, 0.2 );
		}
		emitter.attributes.colorStart.needsUpdate = true;
		emitter.attributes.colorMiddle.needsUpdate = true;
		emitter.attributes.colorEnd.needsUpdate = true;

You need to replace the RGB vaues with yours.
cheers

**Comment by adarshnambiar** [comment]
@RemusMar  : Thanks a lot ..it works for now :) ..appreciate your quick help.

**Comment by squarefeet** [comment]
Hi all,

I'm making some decent progress on being able to change parameters at runtime, so hopefully I'll have something in a branch for you to take a look at soon!

**Comment by squarefeet** [comment]
Hi again,

I've pushed a new branch called `runtime` that you're welcome to check out. There's a new example called `runtimeChanging.html` that uses DAT.Gui to let you change parameters at runtime. 

I've not done a huge amount of testing across various devices yet, but from what I can tell I've managed to accidentally speed things up ever-so-slightly, so that's never a bad thing.

Let me know if you have any issues/bugs with it.

Cheers!

PS. This branch also includes `fog` support, so if you get any shader compilation errors, let me know as that will be the source for that. Changing attributes at runtime doesn't affect the underlying GLSL, so any GLSL errors will be due to the still-in-progress `fog` support.

**Comment by squarefeet** [comment]
@Usnul - Just tagging you; if you have a spare sec would you mind giving this a whirl? Cheers buddy :)

**Comment by RemusMar** [comment]
> I've pushed a new branch called runtime that you're welcome to check out.
> There's a new example called runtimeChanging.html that uses DAT.Gui to let you change parameters at runtime. 

Well done Luke!
However ... changing at runtime emitter.sizeStart, emitter.sizeMiddle & emitter.sizeEnd works for the UPCOMING particles only.
The size of the current particles is not changed (so they need to "die" to get the right results).

From this point of view, my workaround is still the best solution.
cheers

**Comment by squarefeet** [comment]
Ah - it wasn't made clear that you wanted immediate updates. I'll think about adding in more direct support for this, that will take care of emitter attribute offsets and whatnot (your solution doesn't do that, so if you have more than one emitter in a group, you'll affect all that group's particles).

**Comment by RemusMar** [comment]
> Ah - it wasn't made clear that you wanted immediate updates. 

Luke, it's not about what I want.
Just try to imagine that in some cases the particles do not die at all, so your solution does not work at all.
In my opinion, that loop with emitter.attributes.size.value[ p ].set( ... ); is a the only solution.

http://necromanthus.com/Test/html5/testA.html 
Take a look at the "steam" source and press the right mouse button several times.
This is the perfect result using my workaround.
I want the same result using

		steamEm.sizeStart = 0.4 * zoom;
		steamEm.sizeMiddle = 0.7 * zoom;
		steamEm.sizeEnd = zoom; 

cheers

**Comment by squarefeet** [comment]
I'm well aware of that; it's just a use case that didn't cross my mind, but my point still applies: your solution doesn't take into account that there may be more than one emitter (with different settings) per group - you update all the attributes for all of a group's emitters with the same values.

I've almost got something in place that will allow you to do what you need.

**Comment by squarefeet** [comment]
PS. Once I finish this, you'll be able to do this:

    steamEm.sizeStart = 0.4 * zoom;
    steamEm.sizeMiddle = 0.7 * zoom;
    steamEm.sizeEnd = zoom; 
    steamEm.attributesNeedUpdate = true; // Forces all attributes to be updated immediately

It's a bit of a mess at the moment (not very DRY!), but I'll refactor it once it's stable and works as expected. Will let you know when the `runtime` branch is ready for you to pull.

**Comment by RemusMar** [comment]
> steamEm.attributesNeedUpdate = true; // Forces all attributes to be updated immediately 

I don't think you need to update ALL the emitter attributes.
It will run faster with:

			steamEm.attributes.size.needsUpdate = true;

cheers

**Comment by squarefeet** [comment]
`attributesNeedUpdate` is specific to this library, I just followed the naming convention from THREE.js. It just notifies a few functions in `SPE.Emitter` that all the attributes *that have been changed* for that emitter need to be updated, not just ones that are being respawned.

**Comment by squarefeet** [comment]
Okay, `runtime` branch is ready for you to pull. There's a fair bit of optimisation and whatnot to do, but it seems to be working as you'd like:

    steamEm.sizeStart = 0.4 * zoom;
    steamEm.attributesNeedUpdate = true;

**Comment by RemusMar** [comment]
Well done Luke!

Clear the browser history and try again this link:
http://necromanthus.com/Test/html5/testA.html 

			steamEm.sizeStart = 0.4 * zoom;
			steamEm.sizeMiddle = 0.7 * zoom;
			steamEm.sizeEnd = zoom;
			steamEm.attributesNeedUpdate = true;
			camera.zoom = zoom;
			camera.updateProjectionMatrix();

cheers

**Comment by squarefeet** [comment]
So it's all working fine, yeah? No bugs that you've seen?
