### ISSUE TITLE
Issue when camera is positioned at { x:0, y:0, z:0 }

### ISSUE THREAD

**Issue by webtech1980** [squarefeet/ShaderParticleEngine#73]
Hello and thanks for the great particle engine. For some reason when I position my camera at { x:0, y:0, z:0 } the particles are not rendered. This only seems to happen if I'm using the latest version of the particle engine. I have tested with THREE.js r70 and r71.

**Comment by squarefeet** [comment]
What position are you emitters set to?

**Comment by webtech1980** [comment]
It varies. After updating to the new release my particles weren't being rendered. So I stated playing around with the examples you provided. Your basic example has the camera set to camera.position.z = 50 and the emitter at { 0, 0, 0 }. That works fine but if you switch it around and put the emitter at { 0, 0, 50 } and the camera at { 0, 0, 0 } that's when i'm seeing the issue.

**Comment by squarefeet** [comment]
Ah, found the issue, thanks for letting me know about it - I doubt I would have come across it myself! I've just pushed v0.8.2 that should fix it for you.
