### ISSUE TITLE
alphaTest is not working and there is an error in the documentation

### ISSUE THREAD

**Issue by jungsosh** [squarefeet/ShaderParticleEngine#77]
In the API documentation, alphaTest is declared to be a boolean rather than a number.

More importantly (perhaps related?), in my testing, setting alphaTest to any value seems to not do anything. Using any texture with transparency, setting alphaTest to a value between [0,1] doesn't produce any differences in appearance. Unless alphaTest works differently than in regular three.js, I think something is wrong.

**Comment by squarefeet** [comment]
Hm, odd. I'll take a look, thanks for letting me know.

**Comment by squarefeet** [comment]
Found the problem: I wasn't checking the alpha value against the `ALPHATEST` define in the shader, so nothing was happening. Silly, really.

Fixed now, though. Also updated the docs to fix the other issue you pointed out.
