### ISSUE TITLE
Using the rotation parameter of an emitter causes the position value to be multiplied by -1

### ISSUE THREAD

**Issue by jungsosh** [squarefeet/ShaderParticleEngine#78]
If you set a rotation about some axis and some angle, instead of being located at position (x,y,z), the emitter position becomes (-x,-y,-z) and the rotation is set about that point instead. The expected behavior would be the emitter position stays at (x,y,z), and it rotates about that point (since the default center point is the position).

**Comment by jungsosh** [comment]
Note, the fix for this is super easy. Just multiply the end result of getRotation in rotationFunctions by -1, and the issue seems to be fixed.

**Comment by squarefeet** [comment]
Ha, just done that myself! I'll run a few tests and make sure it doesn't have any unexpected side effects :)

**Comment by jungsosh** [comment]
Thanks for fixing this stuff super quick!

**Comment by squarefeet** [comment]
No worries! The joys of having simple bugs combined with email notifications ;)

**Comment by squarefeet** [comment]
Multiplying by -1.0 inverts the value of the forces being applied (velocity/acceleration)...

**Comment by squarefeet** [comment]
Should be fixed now. Bumped to v1.0.1.
