### ISSUE TITLE
Emitter does not start at Position when a rotation center is defined, and multiple emitters attached to same group affect each other's rotation

### ISSUE THREAD

**Issue by jungsosh** [squarefeet/ShaderParticleEngine#80]
When an emitter has a position as well as a center of rotation defined, instead of starting from position and rotating around the center of rotation, the emitter starts from the inverse position and rotates. Probably related to the fix for #78 

Sorry for making so many issues, I've just had a lot of time to mess around with the engine recently...

**Comment by jungsosh** [comment]
Sorry, also one more bug, if an emitter has a rotation, and then a second emitter is attached to the same group, it seems the second emitter is rotated even if it doesn't have a rotation. 

See this gist: https://gist.github.com/jungsosh/c2c62fc54ae914d77232

The smoke1 emitter's (green one) velocity will flip when the smoke0 emitter's (red one) rotation is applied. Add your own texture to loadTexture, then try commenting the rotation parameter of smoke0 in and out, and smoke1 will flip. Perhaps related to the other bug as well?

**Comment by squarefeet** [comment]
Wow, that is... bizarre! Can't say I know why that's happening (as rotation is a per-particle parameter), but have reproduced it so hold tight for a fix!
