### ISSUE TITLE
Axis of rotation ignores signs

### ISSUE THREAD

**Issue by jungsosh** [squarefeet/ShaderParticleEngine#81]
When you set an axis of rotation, a rotation axis of (-1,1,0) behaves the same as (1,1,0). These should be two different axes, as they are not opposites of each other.

I think I've found the culprit. In getPackedRotationAxis, the absolute value of each component of the axis is taken, thus eliminating all signs. This is presumably done so that it can be packed as a color and then shipped into the shader. However, this process makes axes that shouldn't be equivalent, equivalent.

Normalizing the vector, then adding (1,1,1) to it, and then multiplying by 0.5, and then performing the reverse inside the shader fixes the issue. Perhaps there is a smarter way to do it though.

**Comment by squarefeet** [comment]
You're nailing this! Thanks (no, really) for opening these bugs. Despite my testing, it's very difficult for me to use the library without thinking of what's going on 'under-the-hood', so difficult to catch these things. 

Also thanks for giving possible solutions with your bug reports - super helpful.

I'll add this one to the list!
