### ISSUE TITLE
Issue with editor

### ISSUE THREAD

**Issue by SakyaStelios** [squarefeet/ShaderParticleEngine#84]
Greetings, I'm having some errors with the editor. The console outputs some messages:

    ReferenceError: SPE is not defined
    CONFIG.editor.js:222:3
    TypeError: CONFIG.editor is undefined
    CONFIG.settings-panel.js:24:13
    THREE.WebGLRenderer 71 THREE-r71.min.js:523:216
    ReferenceError: SPE is not defined

**Comment by squarefeet** [comment]
Hi @SakyaStelios, I'm afraid the Editor only supported older versions of the engine. It's on my (very long list) of things to fix :)
