### ISSUE TITLE
Duration ignored when using pools

### ISSUE THREAD

**Issue by Andy888855** [squarefeet/ShaderParticleEngine#85]
Hello,

I tried the engine, I like the idea, but I found some bugs that stop me from using it in my game. One of them is that emitter's duration seems to be ignored when using emitters pools. I changed duration to "duration: 10000" in emitterSettings in "pool.html" example, but emitters still produce particles for no longer then one second.

**Comment by squarefeet** [comment]
Ah, that's probably an oversight on my behalf – I'll add it to the list :)

**Comment by squarefeet** [comment]
Found the problem: there's a conflict between the `duration` and `maxAge` properties.

Say `duration.value` is set to 10, but `maxAge.value` is set to 1: the emitter will only emit for 1 second.
Setting `maxAge.value` to 10 also will fix the problem, but won't get the desired visual effect.

I'll see what's causing this!

**Comment by squarefeet** [comment]
Found a fix, will push to master very shortly.

**Comment by squarefeet** [comment]
Fix is in v1.0.5.

**Comment by DelvarWorld** [comment]
I'm seeing an issue where I'm destroying a group and emitter, and creating a new one with a new maxAge, but the maxAge is being ignored. Could this be related @squarefeet ?

**Comment by squarefeet** [comment]
Any chance you could put together a little JSFiddle? You could fork [this one](https://jsfiddle.net/vkv5vvpz/1/) as a base.

**Comment by DelvarWorld** [comment]
@squarefeet oh this was my mistake, I was sending in the value as a string instead of a number. I think it would be nice if the ensure typed arg stuff logs warnings if you send non-undefined values that don't match the expected type. otherwise it just creates a lot of user confusion!

**Comment by squarefeet** [comment]
Ah phew! Good call on the logging. I'll make a ticket for it.
