### ISSUE TITLE
Particle position

### ISSUE THREAD

**Issue by verteAzur** [squarefeet/ShaderParticleEngine#89]
Hello squarefeet,
I wanted to thank you for your latest SPE work, it performs very well on all aspects. 

This is not an issue per say, it is more a feature request or a question, but there is no way to contact you via email or other messaging tool. I have integrated your library into a video game and would like to know if there is a way to access a particle position at any given time in order to interact with it? I tried to look into the scripts and the code is very complex. Thank you for all!

Cordially,
verteAzur

**Comment by squarefeet** [comment]
Unfortunately not, @verteAzur. The calculations for a particle's position are all stateless (meaning that for each frame, the position of a particle is re-calculated based on its age as opposed to storing the position after each frame and then adding forces to it before saving it again). Because it's stateless, there's no actual position to look up. I'm not very good at describing things, so [here](http://www.gamasutra.com/view/feature/130535/building_a_millionparticle_system.php)'s a good write-up on stateless particle systems.

Once WebGL2 has decent penetration, it adds a wonderful thing called transform-feedback which should allow for a state-preserving particle system. Of course, I could do it with the current version of WebGL using frame-buffer objects (FBOs, or rendering to a texture) but support for FBO/RTT isn't as wide as I'd like.

**Comment by verteAzur** [comment]
Thank you for your detailed reply... It makes sense. Please keep in mind this function/feature would make a huge difference in today gaming market. I was really pleased to just "plug and play" your library into the game engine. A pretty rare things these days. I guess you give someone a hand he'll want the whole arm ;) Anyway, thanks again for that great piece of code!

**Comment by squarefeet** [comment]
No worries, glad you're enjoying the library! Having the ability to lookup particle positions is definitely something that's on the roadmap in my head - I've actually got a few versions knocking around that use FBOs but they're _very_ far from being production ready! One day...

**Comment by verteAzur** [comment]
Cool, it is a sure thing! Keep me in the loop if you need someone for
testing or doing other stuff...

Not to change subject, I have gone far into the development of a game
engine that uses 99% open source tech. I am really thinking about sharing
that code the same way you did via an unified system I have developed for
the past 15 years. It is a web 2.0 system with 3D, I like to call it web
3.0 or web 3D. I am building also a video game  (yeah a second product)
that uses the system at its fullest.  Your particle lib is used everywhere
and I'll try my best to aknowledge it when ever it is used. Another lib is
the water shaders from Fabrice Neyret, another one is the sky shader etc...
I am taking the long way to ask you if you will be interested in joining a
new team for the game and the game engine. In fact you are the first person
I am asking. I would like to have top developers, 3D artits, song writers,
etc from around the world participating into this endeavor for the sake of
"greater goods" and get concret rewards from that hard work. Everyone else
is doing it why not the good people for a change... I know that you have a
lot on your plate like every dev. artist of this world and please don't
feel bad to say no, cause as you know it demands stuff that neither you and
I can anticipate. Today, I feel confortable to move forward in that
direction because the code is robust and the trends are going into the
oposite direction: the dark side, boooo. I have tried to do it alone for
the past 4-5 years thinking that automatic processes and great algorithms
will counter balance it, but I have came to conclusion that the tasks is
larger than a one person army. The ultimate goal is to produce a web 3.0
game engine that could be used by anyone with the intension to help out
human kind. In other words, that engine could never be used to develop a
shooter game nor an horror game nor a game with sexual content, etc...
Yeah, the values and ethics rules will have to be casted into stone at
start by everyone participating. The second goal is to sell the game in a
unique fashion (to be discussed). I know that I can regroup the right
people for these 2 goals this year and maybe have the engine and the game
launch by year end, because I was planning to do it by myself. There is so
much that could be said and I am writing with one toe; if you have an ounce
of interest and want to know more details, I would prefer arranging a
secured voip mumble channel. Anyways, thanks for all you have done thus far
and listening and hope to talk you later...


2016-02-16 12:59 GMT+01:00 Luke Moody <notifications@github.com>:

**Comment by minemeraj** [comment]
@verteAzur hi, I see there is no other way to communicate with you, I hope you will get my message by this comment.

Here I see someone mentioned protecting glb file: https://discourse.threejs.org/t/is-there-a-way-to-not-allow-the-user-to-publicly-download-the-3d-model-and-texture-files-that-im-showing/434/3

http://multivers3d.fr/ is down so i can not get any exmaple.

Could you please provide an example of how to encrypt glb/gltf file and then load it?
