### ISSUE TITLE
SPE only displays on one view out of multiple

### ISSUE THREAD

**Issue by phoenixinwater** [squarefeet/ShaderParticleEngine#90]
Hi, I am attempting to combine this example: http://threejs.org/examples/webgl_multiple_views.html with the SPE explosion example, however the particles only appear on the first view instance. Is this by design or an error on my part? Would you be able to provide any guidance in doing this? 

Thank you for the SPE tool, I have enjoyed using it.

**Comment by squarefeet** [comment]
Hey @phoenixinwater,

I can't say that I've ever tried using this lib in multiple views. Do you have a codepen, jsfiddle, or some code sample I could look at to see if I can figure out what's going on here?

**Comment by phoenixinwater** [comment]
Hey, I have made a test for multiple views with SPE on a different machine and have had no issues. Would you like me to create a jsfiddle?

Also, it may be related, what is the correct method of setting maxParticleCount for the groups?

**Comment by weiserhei** [comment]
@phoenixinwater: you can set maxParticleCount like this:

    	var particleGroup = new SPE.Group({
    	    // ...
            maxParticleCount: 2500
    	});

**Comment by phoenixinwater** [comment]
@weiserhei Cheers mate

**Comment by squarefeet** [comment]
@phoenixinwater What are the differences between the two machines? Different OSes?

**Comment by phoenixinwater** [comment]
@squarefeet I don't have access to the machine I was having issues on atm, but only noticeable difference is that the one with the error had old intel integrated gfx
