### ISSUE TITLE
Blue channel of color is ignored.

### ISSUE THREAD

**Issue by mlsteele** [squarefeet/ShaderParticleEngine#93]
I'm trying to create some particles and I'm finding that the blue channel of color is being ignored. As if it were zero. Putting in white gives orange, putting in blue gives nothing, putting in green gives green.

Am I doing this right? The below code yields entirely green particles where I would expect cyan.

```
        this.particleGroup = new SPE.Group({
            maxParticleCount: 250000,
        })
        this.particleEmitter = new SPE.Emitter({
            particleCount: 5000,
            maxAge: { value: .6, spread: .4 },
            position: {
                value: new THREE.Vector3(250, 0, 80),
                spread: new THREE.Vector3( 10, 10, 10 )
            },
            acceleration: {
                value: new THREE.Vector3(0, 0, 0),
                spread: new THREE.Vector3( 0, 0, 0 )
            },
            velocity: {
                value: new THREE.Vector3(0, 0, 1000),
                spread: new THREE.Vector3(300, 300, 300)
            },
            drag: { value: 0 },
            wiggle: { spread: 100 },
            color: {
                value: new THREE.Color(0, 1, 1),
            },
            opacity: { value: 0.2 },
            size: {
                value: 20
            },
        });
```

**Comment by squarefeet** [comment]
Everything looks okay, except you're not giving a texture to the particleGroup.

I've made a fiddle to make sure the blue channel is being picked up, and it's fine for me: https://jsfiddle.net/hv50vp48/5/

Let me know what you see when you run that.

**Comment by mlsteele** [comment]
You're right. The issue was that I had not included a texture at all.

That fiddle looks good to me, teal fountain. I added a texture to my program's ParticleGroup and that fixed the issue for me. Looks like this now:
```
	var particleGroup = new SPE.Group({
	    maxParticleCount: 250000,
	    texture: {
		value: new THREE.TextureLoader().load("images/star_particle.png")
	    },
	})
```

I guess I just didn't realize that a texture is required. Perhaps it would be nice if that was more forcefully mentioned in the docs, perhaps [here](https://squarefeet.github.io/ShaderParticleEngine/docs/api/global.html#GroupOptions). And maybe a console error. Also while trying to fix this I accidentally added the texture property to the emitter instead of the group and that silently didn't work, so an error there could be cool too.

But anyway, that's it for this issue, thanks for the help. :)
