### ISSUE TITLE
Don't commit the build/ folder

### ISSUE THREAD

**Issue by DelvarWorld** [squarefeet/ShaderParticleEngine#96]
Git repos are mainly to version source code, not built/compiled code. There are many reasons for this, one of which is that the version history for a built file is irrelevant, only the source code history is relevant. I don't think the build folder should be committed and there are two easy changes to make:

For npm, we can use a prepublish script to build the package deliverables before publishing to npm.

For users to download, simply put the built file somewhere on a CDN and link to it.

**Comment by squarefeet** [comment]
Sure, in an ideal world, the build folder wouldn't be part of the repo, and I agree re. the point of Git. If I can find a free, reliable CDN that would be willing to host this library, then I'll definitely go down that route. For now, though, I'm keeping the `build` folder as part of the repo.

It's just a matter of ensuring the built version is easily available, really; currently having it as part of this repo is the easiest way. And anyway, the ThreeJS repo is guilty of this sin, too ;)

**Comment by DelvarWorld** [comment]
You could try submitting a request to https://cdnjs.com/

You could also try github file uploads, I haven't worked with those yet.
